name: fundademo
description: "Funda Flutter demo"
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  dio: ^5.6.0
  get_it: ^7.7.0
  intl: ^0.19.0
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/static/OpenSans-Bold.ttf
        - asset: assets/fonts/Open_Sans/static/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/Open_Sans/static/OpenSans-Regular.ttf
        - asset: assets/fonts/Open_Sans/static/OpenSans-Italic.ttf
        - asset: assets/fonts/Open_Sans/static/OpenSans-Medium.ttf
        - asset: assets/fonts/Open_Sans/static/OpenSans-MediumItalic.ttf
